version: '3.8'

services:
  db:
    image: postgres:14.6-alpine
    environment:
      POSTGRES_DB: postgres_drf_2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Daana777
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: "redis:alpine"

  web:
    build: .
    command: gunicorn drf.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  celery:
    build: .
    command: celery -A drf worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - web
      - db
      - redis

volumes:
  pgdata:
    driver: local
